# Generated by Django 3.2.4 on 2021-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('originality', models.CharField(max_length=50, verbose_name='Оригинальность')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Бренд')),
                ('finis', models.CharField(max_length=50, verbose_name='Артикул')),
                ('goods_name', models.CharField(default='', max_length=150, verbose_name='Описание')),
                ('delivery_date', models.CharField(max_length=20, verbose_name='Срок доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('image_url', models.CharField(max_length=50, verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
    ]
