# Generated by Django 3.2.4 on 2021-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title of site')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('user_login', models.CharField(max_length=50, verbose_name='Login')),
                ('user_password', models.CharField(max_length=50, verbose_name='Password')),
                ('domain', models.CharField(max_length=250, verbose_name='Session domain')),
                ('name', models.CharField(max_length=250, verbose_name='Session name')),
                ('value', models.CharField(max_length=250, verbose_name='Session value')),
                ('path', models.CharField(max_length=250, verbose_name='Session path')),
            ],
        ),
        migrations.CreateModel(
            name='Xhr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of site')),
                ('remember_me', models.CharField(max_length=200, verbose_name='REMEMBER_ME from headers')),
                ('legacyapp', models.CharField(max_length=200, verbose_name='LegacyApp from headers')),
            ],
        ),
    ]
