# Generated by Django 3.2.4 on 2021-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdateCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of site')),
                ('date_of_last_update', models.DateTimeField(verbose_name='Date of last update cookies for profile')),
            ],
        ),
    ]
