# Generated by Django 3.2.4 on 2021-10-21 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_lastupdatecookie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastupdatecookie',
            name='title',
            field=models.CharField(default=(2011, 1, 1), max_length=100, verbose_name='Last update'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastupdatecookie',
            name='date_of_last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Date of last update cookies for profile'),
        ),
    ]
